P8105\_HW1\_hw2849
================
Haotian Wu

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

### Create a data frame

Creating a data frame contains: a random sample of normal distribution,
a logical vector, a character vector, and a factor vector.

``` r
df <- tibble(
  
  set.seed(10),
  
  ## a random sample of size 10 from a standard Normal distribution
  sample_set = rnorm(10), 
  
  ## a logical vector indicating whether elements of the sample are greater than 0
  log_vec = c(sample_set > 0), 
  
  ## a character vector of length 10
  char_vec = c("This", "is", "a", "character", "vector", "which", "contains", "10", "random", "characters"),
  
  ## a factor vector of length 10, with 3 different factor “levels”
  fac_vec = factor(c("tall", "grande", "venti", "grande", "venti", "grande", "tall", "venti", "grande", "tall"))
  
)
df
```

    ## # A tibble: 10 × 4
    ##    sample_set log_vec char_vec   fac_vec
    ##         <dbl> <lgl>   <chr>      <fct>  
    ##  1     0.0187 TRUE    This       tall   
    ##  2    -0.184  FALSE   is         grande 
    ##  3    -1.37   FALSE   a          venti  
    ##  4    -0.599  FALSE   character  grande 
    ##  5     0.295  TRUE    vector     venti  
    ##  6     0.390  TRUE    which      grande 
    ##  7    -1.21   FALSE   contains   tall   
    ##  8    -0.364  FALSE   10         venti  
    ##  9    -1.63   FALSE   random     grande 
    ## 10    -0.256  FALSE   characters tall

### Take the mean of each variable

``` r
## mean of the random sample of size 10 from a normal distribution
mean(pull(df, 1))
```

    ## [1] -0.4906568

``` r
## mean of the logical vector
mean(pull(df, 2))
```

    ## [1] 0.3

``` r
## mean of the character vector
mean(pull(df, 3))
```

    ## Warning in mean.default(pull(df, 3)): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

``` r
## mean of the factor vector
mean(pull(df, 4))
```

    ## Warning in mean.default(pull(df, 4)): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

As the results shown, we can take means of the sample size and the
logical vector, but not for for the character vector or the factor
vector.

### Convert variables

Use `as.numeric` function to the logical, character, and factor
variables

``` r
## logical vector
as.numeric(pull(df, 2))

## character vector
as.numeric(pull(df, 3))

## factor vector
as.numeric(pull(df, 4))
```

Apply the as.numeric function to the logical, character, and factor
variables. The results return a list of numbers for logical variable and
factor variable. It explains there exists a mean for logical variable
since it consider `TRUE` as `1` and `FALSE` as `0`, and it returns a
mathematical mean for logical vector.

## Problem 2

### A short description of the dataset

``` r
data("penguins", package = "palmerpenguins")

summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

The size of the dataset is 344 rows and 8 columns. It contains penguins
species and their habits, bill length and depth, flipper length, body
mass, sex and ages. These penguins contain 165 female penguins and 168
male penguins, born between 2007 and 2009. The mean of flipper length is
200.9.

### scatter plot

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm)) + geom_point() + aes(color = species)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_hw2849_files/figure-gfm/scatter-1.png)<!-- -->

``` r
ggsave("penguins_scatterplot.pdf")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).
